# Generated by Django 4.1.2 on 2022-10-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('short_link', models.TextField()),
                ('long_link', models.TextField()),
            ],
            options={
                'db_table': 'Connection',
            },
        ),
    ]
