name: API CI

on:
  push:
    branches: [ "main" ]
    paths:
      - api/**
      - .github/workflows/api-pipeline.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - api/**
      - .github/workflows/api-pipeline.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./api
      run: |
        python manage.py test

  package:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
        - uses: docker/setup-buildx-action@v1

        - uses: docker/login-action@v1
          with:
            username: llanos1205
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - uses: docker/build-push-action@v2
          with:
            context: ./api
            push: true
            file: ./api/DockerFile
            tags: llanos1205/url-jumper:latest