# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - client/**
      - .github/workflows/client-pipeline.yml
  pull_request:
    branches: ["main"]
    paths:
      - client/**
      - .github/workflows/client-pipeline.yml

jobs:
  build-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: build package
        run: npm run build-dev
        working-directory: ./client

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: client_artifact
          path: ./client/dist/*

  deploy-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: client_artifact
          path: ./client_artifact
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: push to s3
        run: aws s3 sync ./client_artifact s3://dev.llanoscorp.com --region us-east-1 --cache-control max-age=0 --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  