# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CI

on:
  push:
    branches: [ "main" ]
    paths:
      - client/**
      - .github/workflows/client-pipeline.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - client/**
      - .github/workflows/client-pipeline.yml

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json
        
    - name: Install Dependencies
      run: npm install
      working-directory: ./client
      
    - name: build package
      run: npm run build 
      working-directory: ./client

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: client_artifact
        path: ./client/dist/*

 
